import React from "react";

export default function Links() {
  return (
    <main
      className="
           text-white
            text-xl
             w-[90%]
             h-10
             md:h-1
                    flex
                    items-center
                    justify-around
                    z-10
                "
    >
      <a
        href="https://www.linkedin.com/in/daniperezbnc/"
        target="_blank"
      >
        <button
          className="
              w-24
              h-full
             
              flex
              text-center
              justify-center
              items-center
              rounded-[40px]
              bg-indigo-300
              p-3
          "
        >
          <h3>Linkedin</h3>
        </button>
      </a>
      <a
        href="https://www.domestika.org/es/nneodani/portfolio"
        target="_blank"
      >
        <button
          className="
              w-28
              h-full
              rounded-[40px]
              bg-indigo-300
              p-3
          "
        >
          Domestika
        </button>
      </a>
      <a href="https://github.com/Dani-Bcn"  target="_blank">
        <button
          className="
              w-24
              h-full
              rounded-[40px]
              bg-indigo-300
              p-3
          "
        >
          GitHub
        </button>
      </a>
    </main>
  );
}
